version: '3'
services:
  app:
    build: .

    ports:
      - "8000:8000"
    volumes:
      - .:/app
#    links:
#      - db
#  db:
#    image: mongo:latest
#    hostname: test_mongodb
#    environment:
#      - MONGO_INITDB_DATABASE=users
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=pass